name: Run Citus Tests

on:
  push:
    branches:
      - 'tpch/**'
      - 'pgbench/**'

jobs:
  run_citus_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Fabric and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fabric==2.6.0

      - name: Run TPCH Test
        if: startsWith(github.ref, 'refs/heads/tpch/')
        run: |
          cd test-automation
          fab run_tpch_tests

      - name: Run PgBench Test
        if: startsWith(github.ref, 'refs/heads/pgbench/')
        run: |
          cd test-automation
          fab run_pgbench_tests

      - name: Upload Test Logs (optional)
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: test-automation/output_logs/
